# Generated by Django 5.1 on 2026-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emailid',
            field=models.EmailField(blank=True, help_text='Primary email address for the user', max_length=254, null=True, unique=True),
        ),
    ]
